server:
  port: 6060

spring:
  application:
    name: great
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
  datasource:
    url: jdbc:postgresql://localhost/greatness
    username: postgres
    password: Luger9mm
      
logging:
  level: 
    com.greatness: DEBUG
    org.hibernate: error
  file: 
    name: logs/greatness.log
    max-size: 2000kb
    max-history: 5
    
    
    
    
  
      
  