spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      initial-size: 50
      max-active: 100
      max-idle: 100
      min-idle: 50
      max-wait: 30000
      
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update