server:
  port: 6060

spring:
  application:
    name: great
  datasource:
    url: jdbc:postgresql://localhost/greatness
    username: postgres
    password: Luger9mm
      
logging:
  level: 
    com.greatness: DEBUG
    org.hibernate: error
  
      
  